# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [jack, grub]
patreon: # Replace with a single Patreon username justinfamily.family.blog
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username yoshi
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username webull
issuehunt: # Replace with a single IssueHunt username Tor
otechie: # Replace with a single Otechie username zacks
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://netspend.com','https://crest.com' ,'https://pink.com','https://ring.com', 'https://pornhub.com']
